AllCops:
  # Depreciated RunRailsCops - start
  # RunRailsCops: true
  Rails:
    Enabled: true
  # Depreciated RunRailsCops - end
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
